AWS_ACCESS_KEY_ID: 'AKIAJLPLRXPLNMGJVV3A'
AWS_ACCESS_SECRET_KEY: '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'
AWS_REGION: 'eu-west-2'
AWS_BUCKET: 'bcgdv-test'
AMQP_URI: 'pyamqp://guest:guest@rabbit'
serializer: 'pickle'
