version: "3"


x-common-variables: &common-variables
  AWS_ACCESS_KEY_ID: setme
  AWS_ACCESS_SECRET_KEY: setme

services:
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3.6-management
    ports:
        - "15672:15672"
    restart: always

  image:
    build: .
    image: nameko_service
    command: nameko run --config=config.yml services.image
    depends_on:
      - rabbit
    ports:
        - "8000:8000"
    links:
        - "rabbit:rabbitmq"

    restart: always
    environment: *common-variables


  convert:
    build: .
    image: nameko_service
    command: nameko run --config=config.yml services.convert
    depends_on:
      - rabbit
    links:
        - "rabbit:rabbitmq"
    environment: *common-variables
    restart: always

  resize:
    build: .
    image: nameko_service
    command: nameko run --config=config.yml services.resize
    depends_on:
      - rabbit
    links:
        - "rabbit:rabbitmq"
    restart: always
    environment: *common-variables

  rotate:
    build: .
    image: nameko_service
    command: nameko run --config=config.yml services.rotate
    depends_on:
      - rabbit
    links:
        - "rabbit:rabbitmq"

    restart: always
    environment: *common-variables
